[package]
name = "common"
version = "0.1.0"
authors = ["Will Hahne <will07c5@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.3"
base64 = "~0.5.0"
hex = "0.3.2"
rust-crypto = "^0.2"
percent-encoding = "1.0.1"
byteorder = "1.2.7"